### PR TITLE
slack alerter

### PR DESCRIPTION
**Pull request by mcqueenorama**
This sends alerts to slack, using a text/template in the config file to specify the content of the alert.  The default alert has alert text from the mail alert using the event context.

I think it would be better to integrate this with the webhook alerter, but I'd have to remove the webhook struct and anyway, I didn't figure out a generic way to get this going via the template.  If I can get the entire post content to come from the template this would be generic, but I had to do append the template text appended to "payload=".  Maybe you have an idea for how to get that into a single template, and then this would be a decent general webhook, with the post body entirely determined by the template.

Also I was guessing quite a bit to figure out how the config file should look.

### CODE REVIEW

**Comment by mcqueenorama** [comment]
I don't know why this fails the Travis checks.  It seems to work well.  I assumed these Travis failures were not due to some problem on the Travis side.

**Comment by boivie** [comment]
Don't worry about the travis checks - I think it always fails for all pull requests. I must have misconfigured it somehow.

Thanks for the pull request - I'll have a look at it right away!

**Comment by boivie** [comment]
Hi again,

I have merged your changes - but I squashed your commits so github is a bit confused. Also, I did some changes which I hope you will like (using https://api.slack.com/docs/attachments) and documented it at http://lovebeat.readthedocs.org/en/latest/alerters.html#slack

So you will need to change your configuration, but it should be an easy fix.

Thanks for the contribution - Slack alerting is really something I have missed myself!

**Comment by mcqueenorama** [comment]
This is good.  Keep on slugging.

**Pull request closed without merging**
