### PR TITLE
Add Debian packaging

### PR DESCRIPTION
**Pull request by magnusbaeck**
This patch series isn't quite completed but just about, so I thought I'd throw it out there before going on vacation for a week and allow some time for reviewing. There are a couple of XXX placeholders that obviously need to be replaced but otherwise it should be okay.

### CODE REVIEW

**Comment by boivie** [comment]
Thanks Magnus!

I'll have a look at it, and comment. Let's continue with it when you're back from your vacation

**Comment by magnusbaeck** [comment]
I've amended the main commit to correct a few mistakes and make Lintian happier. AFAICT this is good to go.

**Comment by boivie** [comment]
Thanks - I have reviewed it and will test it tomorrow!

**Comment by magnusbaeck** [comment]
Rebased and pushed to master after updating the version in debian/changelog to match the new 1.0.0-rc.1 reality.

**Pull request closed without merging**
